"""added amenity table and many to many relation with property

Revision ID: 9afa42e60569
Revises: 5152c0a0389e
Create Date: 2025-10-10 07:29:27.226063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afa42e60569'
down_revision: Union[str, Sequence[str], None] = '5152c0a0389e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('property_amenities',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'amenity_id')
    )
    op.add_column('properties', sa.Column('parking_spaces', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('heating_type', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('cooling_type', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.drop_column('properties', 'cooling_type')
    op.drop_column('properties', 'heating_type')
    op.drop_column('properties', 'parking_spaces')
    op.drop_table('property_amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
