"""fix: cascade delete relation rows on deletion of property or amenity

Revision ID: a7b5b9be8f23
Revises: 17e0b1d5d46e
Create Date: 2025-10-11 10:08:32.086349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b5b9be8f23'
down_revision: Union[str, Sequence[str], None] = '17e0b1d5d46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('property_amenities_property_id_fkey'), 'property_amenities', type_='foreignkey')
    op.drop_constraint(op.f('property_amenities_amenity_id_fkey'), 'property_amenities', type_='foreignkey')
    op.create_foreign_key(None, 'property_amenities', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'property_amenities', 'amenities', ['amenity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_amenities', type_='foreignkey')
    op.drop_constraint(None, 'property_amenities', type_='foreignkey')
    op.create_foreign_key(op.f('property_amenities_amenity_id_fkey'), 'property_amenities', 'amenities', ['amenity_id'], ['id'])
    op.create_foreign_key(op.f('property_amenities_property_id_fkey'), 'property_amenities', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###
