"""fix: property images now hold list of link instead of single one

Revision ID: ff253175511b
Revises: 9afa42e60569
Create Date: 2025-10-10 08:24:23.031730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff253175511b'
down_revision: Union[str, Sequence[str], None] = '9afa42e60569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_urls', sa.Text(), nullable=True))
    op.drop_column('properties', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('properties', 'image_urls')
    # ### end Alembic commands ###
