SELECT
  id,
  posted_by,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  country,
  price,
  property_type::text AS property_type,
  status::text AS status,
  bedrooms,
  bathrooms,
  area_sqft,
  lot_size_sqft,
  parking_spaces,
  heating_type,
  cooling_type,
  year_built,
  created_at,
  updated_at,
  is_featured,
  image_urls::text AS image_urls
FROM properties;
